version: 1
disable_existing_loggers: False

handlers:
  fileHandler:
    class: logging.FileHandler
    level: ERROR
    formatter: simpleFormatter
    filename: logs/invalid_json.log
    mode: w

formatters:
  simpleFormatter:
    format: '%(asctime)s - %(levelname)s - %(message)s'

loggers:
  root:
    level: ERROR
    handlers: [fileHandler]
    propagate: no